CREATE TABLE Users(
    userID int NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    fname VARCHAR(255) DEFAULT NULL,
    lname VARCHAR(255) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    adminn BOOLEAN DEFAULT 0,
    dname VARCHAR(255) DEFAULT NULL,
    avatar VARCHAR(255) DEFAULT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Primary Key(userID)
);

CREATE TABLE Followers(
    u_ID INT NOT NULL,
    follower_ID INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (u_ID, follower_ID),
    FOREIGN KEY (u_ID) REFERENCES Users(userID),
    FOREIGN KEY (follower_ID) REFERENCES Users(userID)
);

CREATE TABLE Shifts (
    s_ID int NOT NULL,
    u_ID INT NOT NULL, 
    startTime DATETIME NOT NULL,
    endTime DATETIME NOT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (u_ID, startTime, endTime),
    FOREIGN KEY (u_ID) REFERENCES Users(userID)
);


CREATE TABLE Lists (
    listID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    u_ID INT NOT NULL, 
    listName VARCHAR(255) NOT NULL,
    ltype VARCHAR(255) NOT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (u_ID) REFERENCES Users(userID)
);

CREATE TABLE Movies (
    movieID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) DEFAULT NULL,
    releaseDate DATE DEFAULT NULL,
    img VARCHAR(255) DEFAULT NULL,
    ovr DECIMAL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE People (
    personID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    dod DATE DEFAULT NULL,
    role VARCHAR(255) DEFAULT NULL,
    pob VARCHAR(255) DEFAULT NULL,
    fame DECIMAL DEFAULT NULL,
    img VARCHAR(255) DEFAULT NULL,
    bio TEXT NOT NULL,
    website VARCHAR(255) DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Credits (
    pID INT NOT NULL,
    mID INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (pID, mID),
    FOREIGN KEY (pID) REFERENCES People(personID),
    FOREIGN KEY (mID) REFERENCES Movies(movieID)
);

CREATE TABLE Genres (
    genreID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) DEFAULT NULL,
    releaseDate DATE DEFAULT NULL,
    img VARCHAR(255) DEFAULT NULL,
    ovr DECIMAL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Ratings (
    mID INT NOT NULL,
    uID INT NOT NULL,
    rating DECIMAL(2,1) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (uID, mID),
    FOREIGN KEY (uID) REFERENCES Users(userID)
);

CREATE TABLE Reviews (
    u_ID INT NOT NULL,
    mID INT NOT NULL,
    critique TEXT NOT NULL,
    NOD boolean DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (u_ID, mID),
    FOREIGN KEY (u_ID) REFERENCES Users(userID)
);

CREATE TABLE List_Items (
    lID INT NOT NULL,
    mID INT NOT NULL, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (lID, mID),
    FOREIGN KEY (lID) REFERENCES Lists(listID)
);





